USE iron_arena;

INSERT INTO countries (name) VALUES
('Afghanistan'),
('Akrotiri'),
('Albania'),
('Algeria'),
('American Samoa'),
('Andorra'),
('Angola'),
('Anguilla'),
('Antarctica'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Aruba'),
('Ashmore and Cartier Islands'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas, The'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Bassas da India'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bermuda'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Bouvet Island'),
('Brazil'),
('British Indian Ocean Territory'),
('British Virgin Islands'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burma'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Cayman Islands'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Christmas Island'),
('Clipperton Island'),
('Cocos (Keeling) Islands'),
('Colombia'),
('Comoros'),
('Congo, Democratic Republic of the'),
('Congo, Republic of the'),
('Cook Islands'),
('Coral Sea Islands'),
('Costa Rica'),
('Cote d\'Ivoire'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Dhekelia'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Europa Island'),
('Falkland Islands (Islas Malvinas)'),
('Faroe Islands'),
('Fiji'),
('Finland'),
('France'),
('French Guiana'),
('French Polynesia'),
('French Southern and Antarctic Lands'),
('Gabon'),
('Gambia, The'),
('Gaza Strip'),
('Georgia'),
('Germany'),
('Ghana'),
('Gibraltar'),
('Glorioso Islands'),
('Greece'),
('Greenland'),
('Grenada'),
('Guadeloupe'),
('Guam'),
('Guatemala'),
('Guernsey'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Heard Island and McDonald Islands'),
('Holy See (Vatican City)'),
('Honduras'),
('Hong Kong'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Isle of Man'),
('Israel'),
('Italy'),
('Jamaica'),
('Jan Mayen'),
('Japan'),
('Jersey'),
('Jordan'),
('Juan de Nova Island'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea, North'),
('Korea, South'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macau'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Martinique'),
('Mauritania'),
('Mauritius'),
('Mayotte'),
('Mexico'),
('Micronesia, Federated States of'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montserrat'),
('Morocco'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Navassa Island'),
('Nepal'),
('Netherlands'),
('Netherlands Antilles'),
('New Caledonia'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue'),
('Norfolk Island'),
('Northern Mariana Islands'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paracel Islands'),
('Paraguay'),
('Peru'),
('Philippines'),
('Pitcairn Islands'),
('Poland'),
('Portugal'),
('Puerto Rico'),
('Qatar'),
('Reunion'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Helena'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Pierre and Miquelon'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia and Montenegro'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Georgia and the South Sandwich Islands'),
('Spain'),
('Spratly Islands'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Svalbard'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tokelau'),
('Tonga'),
('Trinidad and Tobago'),
('Tromelin Island'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Turks and Caicos Islands'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Virgin Islands'),
('Wake Island'),
('Wallis and Futuna'),
('West Bank'),
('Western Sahara'),
('Yemen'),
('Zambia'),
('Zimbabwe');

INSERT INTO states (parent, name) VALUES 
(244, 'Alabama'),
(244, 'Alaska'),
(244, 'Arizona'),
(244, 'Arkansas'),
(244, 'California'),
(244, 'Colorado'),
(244, 'Connecticut'),
(244, 'Delaware'),
(244, 'Florida'),
(244, 'Georgia'),
(244, 'Hawaii'),
(244, 'Idaho'),
(244, 'Illinois'),
(244, 'Indiana'),
(244, 'Iowa'),
(244, 'Kansas'),
(244, 'Kentucky'),
(244, 'Louisiana'),
(244, 'Maine'),
(244, 'Maryland'),
(244, 'Massachusetts'),
(244, 'Michigan'),
(244, 'Minnesota'),
(244, 'Mississippi'),
(244, 'Missouri'),
(244, 'Montana'),
(244, 'Nebraska'),
(244, 'Nevada'),
(244, 'New Hampshire'),
(244, 'New Jersey'),
(244, 'New Mexico'),
(244, 'New York'),
(244, 'North Carolina'),
(244, 'North Dakota'),
(244, 'Ohio'),
(244, 'Oklahoma'),
(244, 'Oregon'),
(244, 'Pennsylvania'),
(244, 'Rhode Island'),
(244, 'South Carolina'),
(244, 'South Dakota'),
(244, 'Tennessee'),
(244, 'Texas'),
(244, 'Utah'),
(244, 'Vermont'),
(244, 'Virginia'),
(244, 'Washington'),
(244, 'West Virginia'),
(244, 'Wisconsin'),
(244, 'Wyoming'),
(244, 'District of Columbia'),
(244, 'American Samoa'),
(244, 'Guam'),
(244, 'Northern Mariana Islands'),
(244, 'Puerto Rico'),
(244, 'U.S. Virgin Islands'),
(244, 'Baker Island'),
(244, 'Howland Island'),
(244, 'Jarvis Island'),
(244, 'Johnston Atoll'),
(244, 'Kingman Reef'),
(244, 'Midway Atoll'),
(244, 'Navassa Island'),
(244, 'Palmyra Atoll'),
(244, 'Wake Island');

INSERT INTO states (parent, name) VALUES 
(43, 'Alberta'),
(43, 'British Columbia'),
(43, 'Manitoba'),
(43, 'New Brunswick'),
(43, 'Newfoundland and Labrador'),
(43, 'Nova Scotia'),
(43, 'Ontario'),
(43, 'Prince Edward Island'),
(43, 'Quebec'),
(43, 'Saskatchewan'),
(43, 'Northwest Territories'),
(43, 'Nunavut'),
(43, 'Yukon');
